//Generate main function code

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;

//To generate main file
public class MakeMain
{
	InterfaceInfo intInfo;
	String strSaveDirectory;
	
	//Make top of file comments
	MakeMF makeMFCode = null;
	FileToArray fileToArray = null;
	Date dNow = new Date();
	SimpleDateFormat ft = new SimpleDateFormat ("E yyyy.MM.dd 'at' hh:mm:ss a zzz");
	ArrayList<PairingTool<String, String>> FirstDBMetaPair = new ArrayList<PairingTool<String, String>>();
	SelectClause mySCVConverter;
	String strTotalCode = null;
	//Top of file comments
	String strStartComm = "//This code is generated by MakeMain.java\n"
			+ "//Generated time: " + ft.format(dNow)
			+ "\n//\n";
	
	//import
	String strImpt_0 = "import java.sql.*;\n"
			+ "import java.util.ArrayList;\n"
			+ "import java.util.Iterator;\n";
	
	//Main class name
	String strClassName = "MainCreatedCode";
	
	//class declaration
	String strClassDec_1;
	
	//main function beginning and connecting to database
	String strMain_2;
	
	//first scan, while loop
	String strFirstScan_3 = "\t\t\t//Scan the whole database.\n"
			+ "\t\t\twhile(rs.next())\n"
			+ "\t\t\t{\n";
	
	String strSimpleScan = null;
	
	String strPrintResults = null;
	
	String strHavingScan = null;
	
	String strCatchPart_end = "\t\t}\n"
			+ "\t\tcatch (SQLException e)\n"
			+ "\t\t{\n"
			+ "\t\t\te.printStackTrace();\n"
			+ "\t\t}\n"
			+ "\t\tcatch (ClassNotFoundException e)\n"
			+ "\t\t{\n"
			+ "\t\t\te.printStackTrace();\n"
			+ "\t\t}\n"
			+ "\t}\n}\n";
	
	//Initialize data structures, classes and types
	public MakeMain(String saveDir,InterfaceInfo intInfo_orig, FileToArray fileToArray, MakeMF mfstruct, DBMeta info)
	{
		this.strSaveDirectory = saveDir;
		this.intInfo = new InterfaceInfo(intInfo_orig);
		this.strMain_2 = generateIntInfo();
		this.strClassDec_1 = generateDeclaration();
		FirstDBMetaPair = info.getList();
		this.makeMFCode = new MakeMF(mfstruct);
		mySCVConverter = new SelectClause(fileToArray, info);
		this.fileToArray = new FileToArray(fileToArray);
		System.out.println(this.mySCVConverter.FirstConVects.size());
		System.out.println(this.mySCVConverter.FirstHaveCon.size());
		strSimpleScan = this.generateFirstScan();
		strHavingScan = this.generateHaving();
		strPrintResults = this.printResults();
	}
	
	//output created code and save in selected location
	public void printGCode()
	{
		if(strSimpleScan != null)
		{
			strTotalCode = strStartComm + strImpt_0 + strClassDec_1 + strMain_2
					+ strFirstScan_3 + strSimpleScan + strHavingScan + strPrintResults
					+ strCatchPart_end;
			//generate a java file
			try
			{
				PrintWriter pwoutMain = new PrintWriter(new FileWriter(this.strSaveDirectory + "/MainCreatedCode.java"));
				pwoutMain.print(strTotalCode);
				System.out.println("File MainCreatedCode.java successfully generated!");
				pwoutMain.close();
				PrintWriter pwoutMFstruct = new PrintWriter(new FileWriter(this.strSaveDirectory + "/CreatedMF.java"));
				pwoutMFstruct.print(this.makeMFCode.getClassStr());
				System.out.println("File CreatedMF.java successfully generated!");
				pwoutMFstruct.close();
			}
			catch (IOException e) 
			{
				e.printStackTrace();
			}
		}
	}
	
	//The First part of the main file, declaration of all DB needed data.
	private String generateDeclaration()
	{
		return "public class " + strClassName + "\n" + "{\n"
				+ "\t//Declare and initialize all types and data.\n"
				+ "\t" + "static final String JDBC_DRIVER = \"org.postgresql.Driver\";\n"
				+ "\t" + "static final String DB_URL = \"" + intInfo.strDBURL +"\";\n"
				+ "\t" + "static final String user = \"" + intInfo.strDBUserName +"\";\n"
				+ "\t" + "static final String password = \"" + intInfo.strDBPSW + "\";\n"
				+ "\t" + "static Connection connection;\n"
				+ "\t//There might be some unused datatypes, eliminate warning.\n"
				+ "\t" + "@SuppressWarnings(\"unused\")\n";
	}
	
	//To generate first few lines of the main method.
	private String generateIntInfo()
	{
		return "\n\t//main method...\n" +
				"\t" + "static public void main(String arg[])\n" + "\t{\n"
				+ "\t\t//ArrayList stores all the CreatedMF type of data.\n"
				+ "\t\tArrayList<CreatedMF> FirstMFStruct = new ArrayList<CreatedMF>();\n"
				+ "\t\t" + "try\n" + "\t\t{\n"
		+ "\t\t\tClass.forName(JDBC_DRIVER);\n"
				+ "\t\t\tconnection = DriverManager.getConnection(DB_URL, user, password);\n"
		+ "\t\t\tSystem.out.println(\"[Results of the query]\");\n"
		+ "\t\t\tString queryStr = \"SELECT * FROM " + intInfo.strTableName + "\";\n"
		+ "\t\t\tStatement st = connection.createStatement();\n"
		+ "\t\t\tResultSet rs = st.executeQuery(queryStr);\n";
	}
	
	//The first while() loop, for the first scan.
	private String generateFirstScan()
	{
		String tmp = new String();
		for(int i = 0; i != FirstDBMetaPair.size(); i++)
		{
			String name = FirstDBMetaPair.get(i).getFirst();
			String type = FirstDBMetaPair.get(i).getSecond();
			String typeGetMethod = type.substring(0, 1).toUpperCase() + type.substring(1);
			tmp = tmp + "\t\t\t\t" + type + " " + name + "Tmp" + " = rs.get" + typeGetMethod + "(\""
					+ name + "\");\n";
		}
		//Follow code is to print all data. SELECT * FROM <TABLE>
		
		for(int i = 0; i != this.fileToArray.numGroupingVari; i++)
		{
			tmp += "\t\t\t\t//#" + new Integer(i+1) + " Selection Conditions.\n";
			tmp += "\t\t\t\tif(" + this.mySCVConverter.FirstJavaCodeConditions.get(i).getSecond() + ")\n";
			tmp += "\t\t\t\t{\n";
			tmp += "\t\t\t\t\tif(FirstMFStruct.size() == 0)\n";
			tmp += "\t\t\t\t\t{\n";
			tmp += "\t\t\t\t\t\tCreatedMF mfStructTmp = new CreatedMF();\n";
			tmp += "\t\t\t\t\t\tmfStructTmp.initialization_" + new Integer(i+1) + "(";
			tmp += this.makeMFCode.getInitFunctionString();
			tmp += "\t\t\t\t\t\tFirstMFStruct.add(mfStructTmp);\n";
			tmp += "\t\t\t\t\t}\n";
			tmp += "\t\t\t\t\telse\n";
			tmp += "\t\t\t\t\t{\n";
			tmp += "\t\t\t\t\t\tfor(int i = 0; i != FirstMFStruct.size(); i++)\n";
			tmp += "\t\t\t\t\t\t{\n";
			tmp += "\t\t\t\t\t\t\tif(FirstMFStruct.get(i).equals(";
			for(int i0 = 0; i0 != this.makeMFCode.getGroupingTypeNameList().size(); i0++)
			{
				tmp += this.makeMFCode.getGroupingTypeNameList().get(i0).getSecond() + "Tmp";
				if(i0 != this.makeMFCode.getGroupingTypeNameList().size() - 1)
				{
					tmp += ",";
				}
			}
			tmp += ") == true)\n";
			tmp += "\t\t\t\t\t\t\t{\n";
			//Add count_* functions
			tmp += "\t\t\t\t\t\t\t\tFirstMFStruct.get(i).set_count_" + new Integer(i+1)+ "();\n";
			
			ArrayList<PairingTool<Integer, String>> tmpList = new ArrayList<PairingTool<Integer, String>>(
					this.makeMFCode.getFuncitonList());
			for(int j = 0; j != tmpList.size(); j++)
			{
				if(tmpList.get(j).getFirst().equals(i+1))
				{
					tmp += "\t\t\t\t\t\t\t\tFirstMFStruct.get(i).";
					tmp += tmpList.get(j).getSecond() + "(" + 
					this.myInitSubString(tmpList.get(j).getSecond()) + "Tmp" + ");\n";
				}
			}
			tmp += "\t\t\t\t\t\t\t\tbreak;\n";
			tmp += "\t\t\t\t\t\t\t}\n";
			
			tmp += "\t\t\t\t\t\t\tif(i == FirstMFStruct.size() - 1)\n";
			tmp += "\t\t\t\t\t\t\t{\n";
			tmp += "\t\t\t\t\t\t\t\tCreatedMF mfStructTmp = new CreatedMF();\n";
			tmp += "\t\t\t\t\t\t\t\tmfStructTmp.initialization_" + new Integer(i+1) + "("
						+ this.makeMFCode.getInitFunctionString();
			tmp += "\t\t\t\t\t\t\t\tFirstMFStruct.add(mfStructTmp);\n";
			tmp += "\t\t\t\t\t\t\t\tbreak;\n";
			tmp += "\t\t\t\t\t\t\t}\n";
			tmp += "\t\t\t\t\t\t}\n";
			tmp += "\t\t\t\t\t}\n";
			tmp += "\t\t\t\t}\n";
		}
		tmp += "\t\t\t}\n";
		return tmp;
	}
	
	private String generateHaving()
	{
		//System.out.println(this.mySCVConverter.SecondJavaCodeConditions.get(0).getFirst());
		String tmp = new String();
		tmp += "\t\t\t//Having Conditions.\n";
		tmp += "\t\t\tIterator<CreatedMF> StructIterator = FirstMFStruct.iterator();\n";
		tmp += "\t\t\twhile(StructIterator.hasNext())\n";
		tmp += "\t\t\t{\n";
		tmp += "\t\t\t\tCreatedMF MFTmp = StructIterator.next();\n";
		tmp += "\t\t\t\tif((" + this.mySCVConverter.SecondJavaCodeConditions.get(0).getSecond() + ") != true)\n";
		tmp += "\t\t\t\t{\n";
		tmp += "\t\t\t\t\tStructIterator.remove();\n";
		tmp += "\t\t\t\t}\n";
		tmp += "\t\t\t}\n";
		return tmp;
	}
	
	//print results at the last part.
	private String printResults()
	{
		String strReturn = "\t\t\t//to print out the results.\n";
		strReturn += "\t\t\tSystem.out.printf(\"";

		String tmpOutputFormat = new String();
		for(int i = 0; i != this.fileToArray.FirstGroupingAttr.size(); i++)
		{
			strReturn += "%-14s";
			tmpOutputFormat += "%-14s";
		}
		for(int i = 0; i != this.fileToArray.FirstFV.size(); i++)
		{
			strReturn += "%14s";
			tmpOutputFormat += "%14s";
		}
		strReturn += "\\n\", ";
		for(int i = 0; i != this.fileToArray.FirstSelectAttr.size(); i++)
		{
			strReturn += "\"" + this.fileToArray.FirstSelectAttr.get(i).toUpperCase() + "\"";
			if(i != this.fileToArray.FirstSelectAttr.size() - 1)
			{
				strReturn += " , ";
			}
		}
		strReturn += ");\n";
		strReturn += "\t\t\tfor(int i = 0; i != FirstMFStruct.size(); i++)\n";
		strReturn += "\t\t\t{\n";
		strReturn += "\t\t\t\tSystem.out.printf(\"" + tmpOutputFormat + "\\n\", \n\t\t\t\t\t ";
		
		
		
		ArrayList<String> tmpList = this.fileToArray.FirstSelectAttr;
		for(int i = 0; i != tmpList.size(); i++)
		{
			String convertedName = new MakeMF().convertVariableName(tmpList.get(i));
			if(convertedName.startsWith("count") == false)
			{
				strReturn += "FirstMFStruct.get(i)."
						+ convertedName;
			}
			else
			{
				String tmp = this.myInitSubString(convertedName);
				String countName = convertedName.replaceAll("_" + tmp, "");
				strReturn += "FirstMFStruct.get(i)." + countName;
			}
			if(i != tmpList.size() - 1)
			{
				strReturn += " , \n\t\t\t\t\t ";
			}
		}
		strReturn += ");\n";
		strReturn += "\t\t\t}\n";
		return strReturn;
	}
	
	//try to get the sub string from method name
	//set_max_length_1 => length
	private String myInitSubString(String name)
	{
		String strTmp = null;
		int j = 0;
		for(int i = name.length() - 1; i !=  0; i--)
		{
			if(name.charAt(i) == '_' && j == 0)
			{
				j = i;
				continue;
			}
			if(name.charAt(i) == '_' && j != 0)
			{
				strTmp = name.substring(i + 1, j);
				break;
			}
		}
		if(strTmp == null)
		{
			System.out.println("Substring Error");
		}
		return strTmp;
	}
	
	//To printout all stuffs, SELECT * FROM <TABLE>
	@SuppressWarnings("unused")
	private String myPrintAll(ArrayList<PairingTool<String, String>> FirstDBMetaPair, String tmp)
	{
		tmp += "\t\t\t\tSystem.out.println(";
		for(int i = 0; i != FirstDBMetaPair.size(); i++)
		{
			if(i == FirstDBMetaPair.size() - 1)
			{
				tmp = tmp + FirstDBMetaPair.get(i).getFirst() + "Tmp" + ");\n";
			}
			else
			{
				tmp = tmp + FirstDBMetaPair.get(i).getFirst() + "Tmp" + " + \"\\t\" + ";
			}
		}
		return tmp;
	}
}